MP/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('MP.views',
	url(r'^$','index_view',name='vista_principal'),
	url(r'^registro/$','registro_view',name='vista_registro'),
	url(r'^busqueda/rapida/$','busqueda_rapida_view',name='busqueda_rapida'),
	url(r'^pruebita/$','pruebita',name='pruebita'),
	url(r'^login/$','login_view',name='vista_login'),
	url(r'^logout/$','logout_view',name='vista_logout'),
	url(r'^perfil/$','perfil_view',name='vista_perfil'),
	url(r'^nuevaclave/$','nuevaclave_view',name='vista_nuevaclave'),
	url(r'^bandejaentrada/$','bandejaentrada_view',name='vista_bandejaentrada'),
	url(r'^editarperfil/$','editarperfil_view',name='vista_editarperfil'),
	url(r'^detalle/socio/(\d+)/$','detalle_socio_view',name='vista_detalle_socio'),
	url(r'^detalle/socio/$','detalle_socio_folio_view',name='vista_detalle_socio_folio'),
	url(r'^enviarPM/$','enviar_mensaje_view',name='enviar_mensaje_personal'),
	url(r'^busqueda/avanzada/$','busqueda_view',name='busqueda_avanzada'),
	url(r'^resultados/$','resultados_view',name='vista_resultados'),
	url(r'^todosresultados/$','resultados_completos',name='vista_resultados_completos'),
	url(r'^mensaje/(\d+)/$','mensaje_view',name='vista_mensaje'),
	url(r'^eliminar/mensaje/(\d+)/$','eliminarmensaje_view',name='vista_eliminarmensaje'),
	url(r'^pago/perfil/$','pagoperfil_view',name='vista_pagoperfil'),
	url(r'^listadopagos/$','listado_view',name='vista_listado'),
	url(r'^infopago/$','infopago_view',name='vista_infopago'),
)    

mipega/urls.py
from django.conf.urls import patterns, include, url
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mipega.views.home', name='home'),
    # url(r'^mipega/', include('mipega.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('MP.urls')),
)

MP/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth import authenticate, login
from datetime import date,timedelta
from calendar import mdays

sexo=(
	('m','Masculino'),
	('f','Femenino'),
)
estadoCivil=(
	('sol','Soltero'),
	('cas','Casado'),
	('div','Divorciado'),
	('anu','Anulado'),
)
tipoContrato=(
	('inde','Indefinido'),
	('def','Definido'),
	('otr','Otro'),
)
planes=(
	('1','Plan 1: $6000 - 6 meses'),
	('2','Plan 2: $8000 - 8 meses'),
	('3','Plan 3: $11000 - 12 meses'),
)
nivelHabilidad=(
	('u','Usuario'),
	('m','Medio'),
	('a','Avanzado'),
)
estadoEstudio=(
	('i','Incompleto'),
	('c','Cursando'),
	('co','Completo'),
)
tipoTitulo=(
	('t','Tecnico'),
	('tp','Tecnico Profesional'),
	('p','Profesional'),
)
tipoLocalidad=(
	('c','Comuna'),
	('r','Región'),
)
hijos=(
	('s','Si'),
	('n','No'),
)
renta=(
	('0','< 200.000'),
	('1','200.000-450.000'),
	('2','450.000-650.000'),
	('3','650.000-850.000'),
	('4','850.000-1.000.000'),
	('5','1.250.000-1.500.000'),
	('6','1.500.000-1.750.000'),
	('7','2.000.000-2.500.000'),
	('8','2.500.000-3.000.000'),
	('9','3.000.000 o +'),
)
estados=(
	('0', 'Activo'),
	('1', 'Inactivo'),
	)
disp=(
	('0', 'Inmediata'),
	('1', '30 días'),
	('2', '60 días'),
	('3', '90 días'),
	)

class Nacionalidad(models.Model):
	id 				  = models.AutoField('ID', primary_key=True)
	nombre 			  = models.CharField('Nombre', max_length=64, null=False, blank=False)

	def __unicode__(self):
		return u'%s' % (self.nombre)

class Socio(models.Model):
	id                = models.AutoField('ID', primary_key=True)
	nombre            = models.CharField('Nombre', max_length=64,null=True, blank=True)
	telefono          = models.IntegerField("Teléfono", null=True, blank=True)
	web               = models.CharField('Web' ,max_length=128, null=True, blank=True)
	edad              = models.IntegerField('Edad', null=True, blank=True)
	sexo              = models.CharField("Sexo",max_length=10, choices=sexo, null=True, blank=True)
	tiene_hijos       = models.CharField('¿Tiene hijos?',max_length=10, choices=hijos, null=True, blank=True)
	estado_civil      = models.CharField('Estado Civil',max_length=10, choices=estadoCivil, null=True, blank=True)
	pretencion_renta  = models.CharField("Pretenciones de Renta", max_length=10, choices=renta, null=True, blank=True)
	tipo_contrato     = models.CharField('Tipo de Contrato',max_length=10, choices=tipoContrato, null=True, blank=True)
	comentario_est	  = models.CharField('Comentario' ,max_length=512, null=True, blank=True)
	folio			  = models.CharField('Folio', max_length=10, null=False, blank=False, unique=True)
	magister		  = models.BooleanField('Magister')
	doctorado 		  = models.BooleanField('Doctorado')
	disponibilidad    = models.CharField('Disponibilidad', max_length=10, choices=disp, null=True, blank=True)
	disponibilidadV	  = models.BooleanField('Dispopnibilidad de vehiculo')
	cargo_extra 	  = models.CharField('Cargos extra' ,max_length=512, null=True, blank=True)
	activo 			  = models.CharField('Estado', max_length=2, choices=estados, default="1")
	
	nacionalidad  =models.ForeignKey(Nacionalidad, verbose_name="Nacionalidad", null=True, blank=True)
	user = models.OneToOneField(User)
	

class RegistroPago(models.Model):
	id           = models.AutoField('ID', primary_key=True)
	fecha_inicio = models.DateTimeField('Fecha Inicio',editable=False, auto_now=True)
	fecha_fin    = models.DateTimeField('Fecha Fin',editable=False)
	plan         = models.CharField('Plan', max_length=7,choices=planes, default="1")

	# Llaves foraneas
	socio        = models.ForeignKey(Socio, verbose_name="Socio")

	def __unicode__(self):
		return u'%s %s' % (self.socio.usuario, self.fecha_inicio)
	class Meta:
		ordering = ["fecha_inicio"]

	def __unicode__(self):
		return u'%s [%s-%s]' % (self.socio, self.fecha_inicio, self.fecha_fin)


class Mensaje(models.Model):
	id              = models.AutoField('ID', primary_key=True)
	fecha           = models.DateTimeField('Fecha',editable=False)
	contenido       = models.CharField('Mensaje', max_length=440,null=False, blank=False)
	nombre_contacto = models.CharField('Nombre', max_length=25,null=False, blank=False)
	medio_contacto  = models.CharField('Contacto', max_length=25,null=False, blank=False)
	leido 			= models.BooleanField('Leido',default=False) 

	# Llaves foraneas
	socio           = models.ForeignKey(Socio, verbose_name="Socio")
	def __unicode__(self):
		return u'(%s) %s' % (self.fecha, self.socio)

class TipoHabilidad(models.Model):
	id     = models.AutoField('ID', primary_key=True)
	nombre = models.CharField('Nombre', max_length=128,null=False, blank=False)

	def __unicode__(self):
		return u'%s' % (self.nombre)


class Habilidad(models.Model):
	id            = models.AutoField('ID', primary_key=True)
	nombre        = models.CharField('Nombre', max_length=128,null=False, blank=False)

	# Llaves foraneas
	tipoHabilidad = models.ForeignKey(TipoHabilidad, verbose_name="Tipo")

	def __unicode__(self):
		return u'%s' % (self.nombre)
	class Meta:
		ordering = ["nombre"]

class OtrasHabilidades(models.Model):
	id        = models.AutoField('ID', primary_key=True)
	nivel     = models.CharField('Nivel', max_length=7,choices=nivelHabilidad, null=True, blank=True)

	# Llaves foraneas
	socio     = models.ForeignKey(Socio, verbose_name="Socio")
	habilidad = models.ForeignKey(Habilidad, verbose_name="Habilidad", null=True, blank=True)



class Rubro(models.Model):
	id     = models.AutoField('ID', primary_key=True)
	nombre = models.CharField('Nombre', max_length=128,null=False, blank=False)

	def __unicode__(self):
		return u'%s' % (self.nombre)
	class Meta:
		ordering = ["nombre"]	

class Cargo(models.Model):
	id     = models.AutoField('ID', primary_key=True)
	nombre = models.CharField('Nombre', max_length=250,null=False, blank=False)

	def __unicode__(self):
		return u'%s' % (self.nombre)
	class Meta:	
		ordering = ["nombre"]

class EmpleoBuscado(models.Model):
	id    = models.AutoField('ID', primary_key=True)

	# Llaves foraneas
	socio = models.ForeignKey(Socio, verbose_name="Socio")
	cargo = models.ForeignKey(Cargo, verbose_name="Cargo", null=True, blank=True)



class ExperienciaLaboral(models.Model):
	id              = models.AutoField('ID', primary_key=True)
	desde           = models.IntegerField("Desde", null=True, blank=True)
	hasta           = models.IntegerField("Hasta", null=True, blank=True)
	comentario      = models.CharField('Comentario', max_length=512, blank=True)

	# Llaves foraneas
	cargo       = models.ForeignKey(Cargo, verbose_name="Cargo", null=True, blank=True)
	socio       = models.ForeignKey(Socio, verbose_name="Socio")
	rubro       = models.ForeignKey(Rubro, verbose_name="Rubro", null=True, blank=True)


class Titulo(models.Model):
	id      = models.AutoField('ID', primary_key=True)
	nombre  = models.CharField('Nombre', max_length=128,null=False, blank=False)
	tipo    = models.CharField('Tipo', max_length=7, choices=tipoTitulo, default="t")

	def __unicode__(self):
		return u'%s' % (self.nombre)
	class Meta:
		ordering = ["nombre"]

class Institucion(models.Model):
	id      = models.AutoField('ID', primary_key=True)
	nombre  = models.CharField('Nombre', max_length=128,null=False, blank=False)
	colegio = models.BooleanField('Colegio') 

	def __unicode__(self):
		return u'%s' % (self.nombre)
	class Meta:
		ordering = ["nombre"]

class Estudios(models.Model):
	id          = models.AutoField('ID', primary_key=True)
	estado      = models.CharField('Estado', max_length=7, choices=estadoEstudio, null=True, blank=True)

	# Llaves foraneas
	titulo      = models.ForeignKey(Titulo, verbose_name="Titulo", null=True, blank=True)
	institucion = models.ForeignKey(Institucion, verbose_name="Institucion", null=True, blank=True)
	socio       = models.ForeignKey(Socio, verbose_name="Socio")


#Ver bien el funcuionamiento de esta tabla
class TitulosEnInstituciones(models.Model):
	#tabla resultante de una relacion n-n
	id          = models.AutoField('ID', primary_key=True)

	#llaves foraneas
	titulo      = models.ForeignKey(Titulo, verbose_name="Titulo")
	institucion = models.ForeignKey(Institucion, verbose_name="Institucion")


class Localidad(models.Model):
	id     = models.AutoField('ID', primary_key=True)
	nombre = models.CharField('Nombre', max_length=128,null=False, blank=False)
	tipo   = models.CharField('Tipo', max_length=7, choices=tipoLocalidad, default="c")

	localidadPadre = models.ForeignKey('self', null=True, blank=True,verbose_name="Pertenece a")
	
	def __unicode__(self):
		return u'%s' % (self.nombre)
	class Meta:
		ordering = ["nombre"]

class LocalidadConSocio(models.Model):
#tabla resultante de una relacion n-n
	id        = models.AutoField('ID', primary_key=True)

	#llaves foraneas
	socio     = models.ForeignKey(Socio, verbose_name="Socio")
	localidad = models.ForeignKey(Localidad, verbose_name="Localidad", null=True, blank=True)

MP/forms.py
#!/usr/bin/python
# -*- coding: Utf8 -*-
from django import forms
from django.forms.widgets import Input
from datetime import date
from django.forms.fields import ChoiceField
from django.forms.widgets import RadioSelect
from MP.models import *
from django.contrib.auth.models import User


RANGO = (
    ('1','18-22'),
    ('2','23-29'),
    ('3','29-37'),
    ('4','38-44'),
    ('5','44+'),
    )

SEXO = (
    ('m','Masculino'),
    ('f','Femenino'),
    )


class Html5DateInput(Input):
    input_type = 'date'

class UserForm(forms.ModelForm):
    ClaveRepetida = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}),required=True,label='Repita su clave')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}),required=True,label='Clave')
    class Meta:
        model = User
        fields = ('username', 'password','email',)
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder': 'ej: 1234567-5'}),  
            'password': forms.PasswordInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control plain-field', 'placeholder': 'ej: mario.palma@mipega.cl'}),        
        }
    
class SocioForm(forms.ModelForm):
    class Meta:
        model = Socio
        fields = ('nombre','disponibilidad','disponibilidadV','cargo_extra', 'edad','comentario_est','nacionalidad','magister','doctorado','sexo','tiene_hijos', 'estado_civil', 'pretencion_renta', 'tipo_contrato',)
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control','placeholder': 'ej: Mario Palma'}),
            'edad': forms.TextInput(attrs={'class':'form-control','placeholder': 'ej: 25'}),
            'sexo': forms.Select(attrs={'class':'form-control'}),
            'estado_civil': forms.Select(attrs={'class':'form-control'}),
            'pretencion_renta': forms.Select(attrs={'class':'form-control'}),
            'tipo_contrato': forms.Select(attrs={'class':'form-control'}),
            'tiene_hijos': forms.Select(attrs={'class':'form-control'}),
            'nacionalidad': forms.Select(attrs={'class':'form-control'}),
            'comentario_est': forms.Textarea(attrs={'class':'form-control', 'rows':'5'}),
            'cargo_extra':forms.TextInput(attrs={'class':'form-control plain-field','placeholder': 'ej: Profesor, Diseñador'}),
            'disponibilidad': forms.Select(attrs={'class':'form-control'}),
        }

class SocioForm2(forms.ModelForm):
    class Meta:
        model = Socio
        fields = ('nombre', 'activo','disponibilidad','disponibilidadV','cargo_extra','edad','comentario_est','nacionalidad','magister','doctorado','sexo','tiene_hijos', 'estado_civil', 'pretencion_renta', 'tipo_contrato',)
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control plain-field'}),
            'edad': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.Select(attrs={'class':'form-control'}),
            'estado_civil': forms.Select(attrs={'class':'form-control'}),
            'pretencion_renta': forms.Select(attrs={'class':'form-control'}),
            'tipo_contrato': forms.Select(attrs={'class':'form-control'}),
            'tiene_hijos': forms.Select(attrs={'class':'form-control'}),
            'nacionalidad': forms.Select(attrs={'class':'form-control '}),
            'comentario_est': forms.Textarea(attrs={'class':'form-control', 'rows':'5'}),
            'cargo_extra':forms.TextInput(attrs={'class':'form-control plain-field'}),
            'activo': forms.Select(attrs={'class':'form-control'}),
            'disponibilidad': forms.Select(attrs={'class':'form-control'}),
        }

class EstudioForm(forms.ModelForm):
    class Meta:
        model = Estudios
        fields = ('estado', 'titulo', 'institucion')
        widgets = {
            'estado': forms.Select(attrs={'class':'form-control'}),
            'titulo': forms.Select(attrs={'class':'form-control'}),
            'institucion': forms.Select(attrs={'class':'form-control'}),        
        }

class ExperienciaLaboralForm(forms.ModelForm):
    class Meta:
        model = ExperienciaLaboral
        fields = ('desde', 'hasta', 'cargo', 'rubro','comentario')
        widgets = {
            'desde': forms.TextInput(attrs={'class':'form-control','placeholder': 'ej: 1989'}),
            'hasta': forms.TextInput(attrs={'class':'form-control','placeholder': 'ej: 2014'}),
            'cargo': forms.Select(attrs={'class':'form-control '}),
            'rubro': forms.Select(attrs={'class':'form-control '}),
            'comentario':forms.Textarea(attrs={'class':'form-control', 'rows':'5'})
        }

class OtrasHabilidadesForm(forms.ModelForm):
    class Meta:
        model = OtrasHabilidades
        fields = ('nivel', 'habilidad',) 
        widgets = {
            'nivel': forms.Select(attrs={'class':'form-control'}),
            'habilidad': forms.Select(attrs={'class':'form-control'}),
        }
                        
#Al parecer no se usa nunca jamás                       
class BuscaRapidaForm(forms.Form):

    cargo = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=False,label='Cargo')
    rango_etario = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}),required=False,label='Rango etario', choices=RANGO)
    localidad = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=False,label='Localidad')
    sexo = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class':'form-control'}),choices=SEXO)


class LoginForm(forms.Form):
    
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

class cambiarClave(forms.Form):
    ClaveAntigua = forms.CharField(max_length=20,  widget= forms.PasswordInput(attrs={'class':'form-control'}),label='Clave antigua')
    ClaveNueva = forms.CharField(max_length=20,  widget= forms.PasswordInput(attrs={'class':'form-control'}),label='Clave nueva:')
    ClaveRepetida = forms.CharField(max_length=20, widget= forms.PasswordInput(attrs={'class':'form-control'}),label='Clave nueva (confirmación):')   

class PagoForm(forms.ModelForm):
    class Meta:
        model = RegistroPago
        fields = ('plan',)
        widget = {
            'plan': forms.Select(attrs={'class':'form-control'}),
        }    

MP/templates/MP/bandejaentrada.html
{% extends 'template.html' %}
{% block title %} Bandeja de entrada | MiPega.cl {% endblock %}
{% block contenido %}

<div class="container">
	<div class="row" style="margin-top:5%;margin-bottom:5%;">
		
		<table class="bandeja table table-striped">
			<tr>
				<th>Estado</th>
				<th>Fecha</th>
				<th>Contacto</th>
				<th>Medio de contacto</th>
				<th>Ver mensaje</th>
				<th>Eliminar mensaje<th>
			</tr>
			{% for mensaje in mensajes %}
				{% ifequal mensaje.leido True %}
					<tr>
						<td>Leido</td>
						<td>{{mensaje.fecha}}</td>
						<td>{{mensaje.nombre_contacto}}</td>
						<td>{{mensaje.medio_contacto}}</td>
						<td><a href="/mensaje/{{mensaje.id}}" class="btn btn-primary btn-small">Ver mensaje</a></td>
						<td><a href="/eliminar/mensaje/{{mensaje.id}}" class="btn btn-warning btn-small">Eliminar</a></td>	
					</tr>
				{% else %}
					<tr>
						<td><b>No leido</b></td>
						<td>{{mensaje.fecha}}</td>
						<td>{{mensaje.nombre_contacto}}</td>
						<td>{{mensaje.medio_contacto}}</td>
						<td><a href="/mensaje/{{mensaje.id}}" class="btn btn-primary btn-small">Ver mensaje</a></td>
						<td><a href="/eliminar/mensaje/{{mensaje.id}}" class="btn btn-warning btn-small">Eliminar</a></td>	
					</tr>
				{% endifequal %}
			{% endfor %}	
		</table>	
	</div>
</div>	
{% endblock %}

MP/templates/MP/nuevaclave.html
{% extends 'template.html' %}
{% block title %} Cambio de clave | MiPega.cl {% endblock %}
{% block contenido %}

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2" style="margin-top:10%;margin-bottom:10%;">
    	<form  action="" method="post">
            {% csrf_token %}
            <div class="block-form-pane">
                <div class="inline-group">
                    <label for="id_ClaveAntigua">Clave actual:</label>
                    {{user_form.ClaveAntigua}}
                </div>
                <div class="inline-group">
                    <label for="id_ClaveNueva">Nueva clave:</label>
                    {{user_form.ClaveNueva}}
                </div>
                <div class="inline-group">
                    <label for="id_ClaveRepetida">Repita su clave:</label>
                    {{user_form.ClaveRepetida}}
                </div>
            </div>
            <input style="margin-top:5%;"class="pull-right btn btn-primary" type="submit" value="Cambiar clave">
        </form>  
      </div>
  </div> 
</div>
{% endblock %}

MP/templates/MP/registro.html
{% extends 'template.html' %}
{% block title %} Registro de usuario | MiPega.cl {% endblock %}
{% block contenido %}

<!--<div id="content">
    <div id="wrapper">--> 
        {% load bootstrap_toolkit %}
        <!--
        <form id="formElem" name="formElem" action="" method="post">-->
        <div id="registro" class="section">
          <div class="bs-callout bs-callout-info" style="margin:3% auto; width:85%;">
            <h3>¡Atención!</h3>
            <p>Mipega es un sitio de búsqueda de trabajo, el cual posee como objetivo  que nuestros socios reciban ofertas laborales de diversas empresas, permitiendo así, a sus participantes, tener un mayor abanico de posibilidades. Para ser visible en nuestro buscador el usuario, deberá cancelar una módica suma de dinero, lo que le permitirá en todo momento modificar su información e inclusive cancelar su subscripción. 
            <strong>Recuerda que una vez registrado, debes pagar tu suscripción para poder aparecer en las busquedas de empresas y agregar los cargos nuevos que ingresaste al sistema.</strong></p>
        </div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 panel panel-default">
                        <div class="panel-body">
                          
                            <form id="myWizard" type="post" method="post" action="{% url 'vista_registro' %}" class="form-horizontal">
                                {% csrf_token %}
                                    {% include "include_templates/registro/step1_perfil.html" %}
                                    
                                    {% include "include_templates/registro/step2_aspiraciones.html" %}

                                    {% include "include_templates/registro/step3_estudios.html" %}
                                    
                                    {% include "include_templates/registro/step4_experiencia.html" %}

                                    {% include "include_templates/registro/step5_otras.html" %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>            
            
{% endblock %}
{% block SCRIPT %}
    <script type="text/javascript" src="{{STATIC_URL}}js/vendor/jquery.easyWizard.js"></script>
    <script>
    $(document).ready(function(){
      
        $(".next").attr("disabled", "disabled");

        $("#id_username").change(function(e){

          if( Rut($("#id_username").val()) ){                       
            $(".next").removeAttr("disabled");  

            if( $("#id_password").val()=="" )
              $(".next").attr("disabled", "disabled"); 
            else
              $(".next").removeAttr("disabled");  

            if( $("#id_ClaveRepetida").val()=="" )
              $(".next").attr("disabled", "disabled"); 
            else
              $(".next").removeAttr("disabled");

            if( $("#id_email").val()=="" )
              $(".next").attr("disabled", "disabled");
            else
              $(".next").removeAttr("disabled");      
             
          } else {
            $(".next").attr("disabled", "disabled");
          }
        });

        $("#id_password").change(function(){

          if( $("#id_password").val()=="" )
            $(".next").attr("disabled", "disabled");
          else
            $(".next").removeAttr("disabled");

          if( $("#id_ClaveRepetida").val()=="" )
              $(".next").attr("disabled", "disabled"); 
            else
              $(".next").removeAttr("disabled");

          if( $("#id_email").val()=="" )
            $(".next").attr("disabled", "disabled");
          else
            $(".next").removeAttr("disabled"); 
        });

        $("#id_ClaveRepetida").change(function(){

          if( $("#id_password").val()=="" )
            $(".next").attr("disabled", "disabled");
          else
            $(".next").removeAttr("disabled");

          if( $("#id_ClaveRepetida").val()=="" )
              $(".next").attr("disabled", "disabled"); 
            else
              $(".next").removeAttr("disabled");

          if( $("#id_email").val()=="" )
            $(".next").attr("disabled", "disabled");
          else
            $(".next").removeAttr("disabled");
        });

        $("#id_email").change(function(){

          if( $("#id_password").val()=="" )
            $(".next").attr("disabled", "disabled");
          else
            $(".next").removeAttr("disabled");

          if( $("#id_ClaveRepetida").val()=="" )
              $(".next").attr("disabled", "disabled"); 
            else
              $(".next").removeAttr("disabled");

          if( $("#id_email").val()=="" )
            $(".next").attr("disabled", "disabled");
          else
            $(".next").removeAttr("disabled");
        });

        //Muestra mas estudios
        $("#mas_titulos").click(function(){
          if( !$("#estudio2").is(":visible") ){
            $("#estudio2").show("slow");            
            $(this).hide();
          }
        });
        
        //Muestra mas experiencias
        $("#mas_experiencias").click(function(){
          if( !$(".experiencia2").is(":visible") ){
            $(".experiencia2").show("slow");
          }else if( !$(".experiencia3").is(":visible") ){
            $(".experiencia3").show("slow");
            $(this).hide();
          }
        });

        //Muestra mas habilidades
        $("#mas_habilidades").click(function(){
          if( !$("#habilidades2").is(":visible") ){
            $("#habilidades2").show("slow");
          }else if( !$("#habilidades3").is(":visible") ){
            $("#habilidades3").show("slow");
            $(this).hide();
          }
        });
      
    });
     $('a.hash').bind('click', function(e) {
                   e.preventDefault();
                   $('html, body').animate({ scrollTop: $(this.hash).offset().top - 45}, 700);
                });

            //$('#navbar').waypoint('sticky');

            
            $('#myWizard').easyWizard({
                submitButtonClass: 'btn btn-success',
                prevButton: 'Atrás',
                nextButton: 'Siguiente',
                submitButtonText: 'Enviar'
            });
    </script> 

{% endblock %}